### PR TITLE
Proposal for Issue #36

### PR DESCRIPTION
**Pull request by Cakmakli-a**
`Validator`

```
protected void validateSchema(final byte[] xmlRawData, final String schemaPath, final int section, final EPart part)
   throws IrrecoverableValidationError {
        URL schemaFile = Validator.class.getResource("/schema/" + schemaPath);
        Source xmlData = new StreamSource(new ByteArrayInputStream(xmlRawData));
        SchemaFactory schemaFactory = SchemaFactory.newInstance("http://www.w3.org/2001/XMLSchema");

        try {
            Schema schema = schemaFactory.newSchema(schemaFile);
            javax.xml.validation.Validator validator = schema.newValidator();
            validator.validate(xmlData);
        } catch (SAXException var10) {
            this.context.addResultItem((new ValidationResultItem(ESeverity.error, "schema validation fails:" + var10)).setSection(section).setPart(part));
        } catch (IOException var11) {
            LOGGER.error(var11.getMessage(), var11);
        }
}
```

### CODE REVIEW

**Comment by jstaerk** [comment]
Thanks for the PR but since ZUV is being merged: do you want to fork or shall we collaborate on integrating the PR into Mustangproject?

**Comment by Cakmakli-a** [comment]
It would be great when the class `Validator` offer a further method which can be called with an URL. (besides the other parameter)
I can not use the full functionality of github (fork & pull) because of network restrictions and i can not bypass these.

**Comment by Cakmakli-a** [comment]
I have to correct myself. The first line in the method 'validateSchema' should be:

`URL schemaFile = Validator.class.getResource("/schema/" + schemaPath);`
This is imho a safe way to load the resource and not depends on the ClassLoader directly.

Sorry, i can not use the full functionality of github because of network restrictions.

**Comment by jstaerk** [comment]
I think it is already that way

**Pull request closed without merging**
